In [1]:
import random
import numpy as np
import itertools
import copy

## Convert x to S

In [2]:
def convert_x_to_S(x):
    x_bar = 0.5*np.ones(len(x))
    s = x >= x_bar
    S = []

    for i in range(len(s)):

        if s[i] == True:
            S.append(i+1)
    
    return S

### F(x) without sampling (not used)

In [3]:
def F_without_sampling(x, f, n, t):
    
    A = [np.array(i) for i in itertools.product([0, 1], repeat = n)]
    
    val_S = 0

    for i in range(len(A)):

        prod_in_s = 1
        prod_not_in_s = 1
        S = []

        for j in range(len(A[i])):
            if A[i][j] == 1:
                prod_in_s = prod_in_s*x[j]
                S.append(j+1)
            else:
                prod_not_in_s = prod_not_in_s*(1-x[j])

        val_S = val_S + f(S)*prod_in_s*prod_not_in_s
    
    return val_S

### Approximation of F(x) using sampling 
define t

In [4]:
def F(x, f, n, t):
    
    sum_R = 0
    
    for i in range(t):
            
        x_bar = np.random.uniform(0,1, n)
        r_t = x >= x_bar
        R_t = []
            
        for i in range(len(r_t)):
            
            if r_t[i] == True:
                R_t.append(i+1)
                
        sum_R = sum_R + f(R_t)

    return sum_R/t

In [5]:
def get_gradient_F_for_i(F, x, f, n, i, t):


    x_without_i = copy.deepcopy(x)
    x_without_i[i] = 0.0

    x_with_i = copy.deepcopy(x)
    x_with_i[i] = 1.0

    # print('x with xi: ', x_with_i)
    # print('x without xi: ', x_without_i)

    df_dxi = F(x_with_i, f, n, t) - F(x_without_i, f, n, t)
    return df_dxi

In [6]:
def get_gradient_F(F, x, f, t):
    
    n = len(x)
    
    grad = np.zeros(len(x))
    
    for i in range(len(x)):
        
        grad[i] = get_gradient_F_for_i(F, x, f, n, i, t)
    
    return grad

## Testing

Define the size of the problem (n) 

In [7]:
n = 10
N = [(i+1) for i in range(n)]

Define an x vector

In [18]:
x = np.random.uniform(0,1, n)
S = convert_x_to_S(x)
print("x: ", x)
print("S: ", S)

x:  [0.04836603 0.37572831 0.41021233 0.12230443 0.80398476 0.65497034
 0.43954222 0.94382951 0.97386578 0.74796854]
S:  [5, 6, 8, 9, 10]


The corresponding S vector

In [19]:
x_init = copy.deepcopy(x)
S_init = copy.deepcopy(S)

In [20]:
t = int(2**n/4)
t

256

## Constant function f(s)

In [21]:
def f_constant(S):
    return 5

### Values of the function

Actual value

In [22]:
f_constant(S)

5

Multi-linear extenstion

In [23]:
F_without_sampling(x, f_constant, n, t)

5.000000000000007

Mutli-linear extension with sampling

In [24]:
F(x, f_constant, n, t)

5.0

### Values of the gradient using multi-linear extension

without sampling

In [25]:
get_gradient_F(F_without_sampling, x, f_constant, t)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

With sampling

In [26]:
get_gradient_F(F, x, f_constant, t)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Linear function f(S)

In [27]:
a = np.random.uniform(-1,1, n)
a

array([ 0.59222674, -0.97487973,  0.96004487,  0.17096135, -0.74982773,
        0.96045825,  0.56990816,  0.59312805,  0.03709839, -0.51428328])

In [31]:
def f_linear(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    return np.dot(a,s_hat)

In [37]:
f_linear([10])

-0.5142832811262776

### Values of the function

Actual value

In [38]:
f_linear(S)

0.32657368284038624

Multi-linear extenstion

In [39]:
F_without_sampling(x, f_linear, n, t)

0.5650785050638427

Mutli-linear extension with sampling

In [40]:
F(x, f_linear, n, t)

0.596814796412228

### Values of the gradient using multi-linear extension

without sampling

In [41]:
get_gradient_F(F_without_sampling, x, f_linear, t)

array([ 0.59222674, -0.97487973,  0.96004487,  0.17096135, -0.74982773,
        0.96045825,  0.56990816,  0.59312805,  0.03709839, -0.51428328])

With sampling

In [42]:
get_gradient_F(F, x, f_linear, t)

array([ 0.56591734, -1.05111496,  0.93707115,  0.2376933 , -0.79388113,
        0.84339722,  0.6563531 ,  0.62721133, -0.1769322 , -0.48996279])

## Polynomial f(S) function

In [43]:
def f_polynomial(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    a_hat = s_hat*a
    
    return np.dot(a_hat,a_hat)

### Values of function

Actual value

In [44]:
f_polynomial(S)

2.102386143805605

Multi-linear extension 

In [45]:
F_without_sampling(x, f_polynomial, n, t)

2.4859144268925633

Multi-linear extenstion with sampling

In [46]:
F(x, f_polynomial, n, t)

2.483450580286315

### Values of gradients using multi-linear approximation

Without sampling

In [47]:
get_gradient_F(F_without_sampling, x, f_polynomial, t)

array([0.35073251, 0.95039049, 0.92168615, 0.02922778, 0.56224162,
       0.92248006, 0.32479531, 0.35180088, 0.00137629, 0.26448729])

With sampling

In [48]:
get_gradient_F(F, x, f_polynomial, t)

array([ 0.35721392,  0.89719282,  1.01751006, -0.01339056,  0.5211119 ,
        0.87695444,  0.33081533,  0.39097011, -0.03839341,  0.16941832])

# Testing Gradient Ascent

## Find maximum using gradient ascent

In [ ]:
def get_gradient_F(F, x, f, t):
    
    n = len(x)
    
    grad = np.zeros(len(x))
    
    for i in range(len(x)):
        
        grad[i] = get_gradient_F_for_i(F, x, f, n, i, t)
    
    return grad

In [83]:
def gradient_ascent(F, x, f, n, alpha, t, epsilon):
    
    x_init = copy.deepcopy(x)
    sum_init = F(x, f, n, t)
    # key values to be used
    sum_update = 0
    iter = 0
    sum_temp = copy.deepcopy(sum_init)

    # start updating the parameters x with iterative gradients
    while np.abs(sum_temp - sum_update) > epsilon:
        iter += 1
        sum_temp = F(x, f, n, t)

        grad = []
        for i in range(n):
            grad_i = get_gradient_F_for_i(F, x, f, n, i, t)
            grad.append(grad_i)
            x[i] = np.minimum(x[i] + alpha * grad_i, 1.0)
            x[i] = np.maximum(x[i], 0.0)
        print('Iter: ', iter)
        print('Grad: ', grad)
        print('x: ', x, '\n')

        sum_update = F(x, f, n, t)

    print('Iterations: ', iter, '\n')
    print('Initial F: ', sum_init)
    print('Initial x: ', x_init, '\n')
    print('Final F: ', sum_update)
    print('Final x: ', x, '\n')
    return iter, sum_update, x

## Go through all the possible S and find the maximum

In [63]:
def actual_max(f,n):
    
    A = [np.array(i) for i in itertools.product([0, 1], repeat = n)]
    
    max_val_S = 0
    argmax_S = []

    for i in range(len(A)):

        S = []

        for j in range(len(A[i])):
            if A[i][j] == 1:
                S.append(j+1)

        val_S = f(S)
        
        if val_S > max_val_S:
            max_val_S = val_S
            argmax_S = S
            print(i,S,val_S)
    
    return max_val_S, argmax_S
    

In [79]:
# stepsize for gradient ascent
alpha = 0.0001
epsilon = 10**(-9)

### For f_linear

In [80]:
x_initial = np.random.uniform(0,1, n)
S_init = convert_x_to_S(x_initial)

In [81]:
print(x_initial,S_init)

[0.96235459 0.50291024 0.7436901  0.58178346 0.62927841 0.84250928
 0.28742754 0.82179082 0.63079153 0.96132735] [1, 2, 3, 4, 5, 6, 8, 9, 10]


In [ ]:
_,_,x_final = gradient_ascent(F, x_initial, f_linear, n, alpha, t, epsilon)
S_final_grad_ascent = convert_x_to_S(x_final)

Iter:  1
Grad:  [0.5902836458740086, -0.8784008105869886, 1.0740856490922719, 0.24090152557908606, -0.7765841286664734, 0.992431204645963, 0.5676864815965166, 0.6182362941914745, 0.026888082106686362, -0.5360619246114429]
x:  [0.96660893 0.4959576  0.75072079 0.58297088 0.62395819 0.84946294
 0.29151072 0.82606692 0.63104885 0.9576027 ] 

Iter:  2
Grad:  [0.6329983832733104, -0.9025476783309767, 0.9624266976171237, 0.2953860266669961, -0.7343971101849096, 0.9394017552568781, 0.5479066575691387, 0.5664688574063141, -0.0863811373825405, -0.5533040483936289]
x:  [0.96667223 0.49586734 0.75081704 0.58300041 0.62388475 0.84955688
 0.29156551 0.82612357 0.63104021 0.95754737] 

Iter:  3
Grad:  [0.4181196881035014, -0.9329766588397517, 0.901748882783429, 0.3117439612930386, -0.777534957818929, 0.9113039062323082, 0.5855386810482412, 0.5624697583023033, 0.12305062956495028, -0.5616425406032435]
x:  [0.96671404 0.49577405 0.75090721 0.58303159 0.62380699 0.84964801
 0.29162406 0.82617982 0.6310

Iter:  26
Grad:  [0.6257005190852762, -1.12280191092159, 0.93593156940584, 0.19272618918694895, -0.6332652411315349, 1.0316754866007731, 0.6189360446088392, 0.6325796335462812, -0.0005393661562889118, -0.569016695561438]
x:  [0.96803525 0.49345682 0.75311369 0.58344374 0.62208453 0.85182913
 0.29287373 0.82755179 0.63108796 0.95629445] 

Iter:  27
Grad:  [0.5778792326552582, -0.9655246438770017, 1.0804373238426632, 0.1395091455706281, -0.7538430040311024, 1.0308677658731344, 0.6588824324480766, 0.552881598802295, 0.05416316102627494, -0.5442277011558223]
x:  [0.96809304 0.49336027 0.75322173 0.58345769 0.62200915 0.85193221
 0.29293962 0.82760708 0.63109338 0.95624002] 

Iter:  28
Grad:  [0.6119683973586518, -0.9932307914996006, 1.038607791961217, 0.22836667878762573, -0.7524930413589828, 0.7950872602317435, 0.46837649599045705, 0.5020125127509476, 0.06196496220403658, -0.49552651529757785]
x:  [0.96815424 0.49326095 0.75332559 0.58348053 0.6219339  0.85201172
 0.29298646 0.82765728 0.

Iter:  52
Grad:  [0.6486653039902215, -1.0555967253553122, 0.8982009128059932, 0.11158152620414019, -0.8446722489133338, 0.8778833743999015, 0.5386332491587305, 0.732054234403707, 0.0251063825158524, -0.4728832044960407]
x:  [0.96956963 0.49085795 0.7556427  0.58383913 0.62011321 0.85432707
 0.29433287 0.82911534 0.63119479 0.95488553] 

Iter:  53
Grad:  [0.6244259472545057, -0.989097054081644, 0.8103323892927151, 0.1633101817054312, -0.8212718795649534, 1.007881638242363, 0.606225989140941, 0.6061788516071867, -0.08246667095710114, -0.4498149956228008]
x:  [0.96963207 0.49075904 0.75572373 0.58385546 0.62003108 0.85442786
 0.2943935  0.82917596 0.63118654 0.95484055] 

Iter:  54
Grad:  [0.6013845323808207, -0.9534799125926439, 0.939611997642256, 0.08467963879644058, -0.8456082255702109, 1.131449732641066, 0.6067076173089974, 0.418941572859558, -0.017055946580380343, -0.5876005836642451]
x:  [0.96969221 0.49066369 0.75581769 0.58386393 0.61994652 0.85454101
 0.29445417 0.82921785 0.631

Iter:  78
Grad:  [0.5761571299914348, -0.9845706930941528, 0.9936861737604065, 0.15317753621772878, -0.7913432925108199, 0.8675462672126034, 0.5139169694852217, 0.6121707491853441, 0.07370996108569705, -0.5207426751436064]
x:  [0.97112541 0.48828295 0.75814329 0.58429186 0.61815901 0.85680612
 0.29579645 0.83063865 0.63126931 0.95357547] 

Iter:  79
Grad:  [0.6237421284242988, -0.9793489071346471, 0.9823392870553347, 0.0651372795547589, -0.7538405934074477, 0.9841149642015139, 0.46089062040737905, 0.4607785731380445, 0.004118552386499497, -0.5194163496267192]
x:  [0.97118779 0.48818502 0.75824152 0.58429837 0.61808362 0.85690453
 0.29584254 0.83068473 0.63126972 0.95352352] 

Iter:  80
Grad:  [0.5799970513678233, -0.97196277675046, 0.9247561316048336, 0.17352736591781315, -0.860330205968838, 0.9670031925241912, 0.7015866427588204, 0.5822203622839707, 0.26342409843525094, -0.5129444675051114]
x:  [0.97124579 0.48808782 0.758334   0.58431573 0.61799759 0.85700123
 0.2959127  0.83074295 0

Iter:  104
Grad:  [0.5987026492271607, -0.9914961685054745, 0.7509546824518484, 0.16717610621139278, -0.747625084802888, 0.9252865749298754, 0.5745294071865008, 0.4929708836920291, 0.05076917347308818, -0.6004858752978413]
x:  [0.97267788 0.48571071 0.76057885 0.5847406  0.61616771 0.85931175
 0.29726445 0.83214779 0.63136366 0.95223826] 

Iter:  105
Grad:  [0.5866188919602418, -0.8349485702577508, 0.8650720292849344, 0.13109128401004821, -0.6931182414081509, 0.9540014967388587, 0.46755099180526627, 0.7297328665982302, -0.002134232053518037, -0.5745649791865888]
x:  [0.97273654 0.48562721 0.76066536 0.58475371 0.6160984  0.85940715
 0.29731121 0.83222077 0.63136345 0.9521808 ] 

Iter:  106
Grad:  [0.5988969205328049, -1.027305989758502, 0.9816398565767679, 0.11250367392769811, -0.6408486240126852, 1.043194199049282, 0.5717001892623317, 0.6506147379095981, -0.16459779901483018, -0.5030557751217464]
x:  [0.97279643 0.48552448 0.76076352 0.58476496 0.61603432 0.85951147
 0.29736838 0.8322

Iter:  128
Grad:  [0.5107496044471425, -0.9721756547485113, 0.9540770170448799, 0.3217403358344706, -0.7377567956116293, 0.9156321085264096, 0.6790086812260969, 0.6529114111660237, 0.058651138002016046, -0.5658469093781067]
x:  [0.97414739 0.48340617 0.76290049 0.58512922 0.61442985 0.86159193
 0.29860254 0.83360577 0.63147758 0.95101981] 

Iter:  129
Grad:  [0.606698084812551, -1.0520626369288126, 1.0285788275959102, 0.2831386243855818, -0.7162612022051713, 0.9137213010756798, 0.6192575192669367, 0.4410345123669672, 0.08520448463571051, -0.6043869913901836]
x:  [0.97420806 0.48330097 0.76300335 0.58515753 0.61435822 0.86168331
 0.29866446 0.83364987 0.6314861  0.95095937] 

Iter:  130
Grad:  [0.5118147194448446, -0.9682466478096265, 0.8596336049816844, 0.17592636267326878, -0.6851227159886066, 1.0774079366039337, 0.5897859734507884, 0.74059296297436, 0.10335042234679692, -0.29959430283544575]
x:  [0.97425924 0.48320414 0.76308931 0.58517512 0.61428971 0.86179105
 0.29872344 0.83372393

Iter:  152
Grad:  [0.60994335941647, -1.0011981620681154, 0.9995232477838961, 0.2143426573554903, -0.8282728563261288, 0.8883312826213857, 0.5158736168314664, 0.6435358828103152, -0.04592844475229829, -0.5718073942494049]
x:  [0.9755261  0.48110419 0.76524163 0.58557502 0.61265803 0.8638729
 0.29988712 0.83507038 0.63160526 0.94975836] 

Iter:  153
Grad:  [0.5565070990379956, -0.9318599845526894, 0.9707112814012504, 0.25528848756062206, -0.8624587455842707, 0.9518620995962663, 0.558709520980414, 0.5729323766816636, 0.001820586691488879, -0.5721056342848474]
x:  [0.97558175 0.48101101 0.7653387  0.58560055 0.61257178 0.86396809
 0.29994299 0.83512767 0.63160544 0.94970115] 

Iter:  154
Grad:  [0.6682589641828531, -1.029100544655518, 0.9815103838689205, 0.1684340970965128, -0.8044290848532161, 0.9494905533289967, 0.5561031799014136, 0.5776017024693292, 0.05899477683002918, -0.44825419886580065]
x:  [0.97564857 0.4809081  0.76543685 0.58561739 0.61249134 0.86406304
 0.2999986  0.83518543 

In [ ]:
a

In [ ]:
print(S_final_grad_ascent)

In [ ]:
max_val,S_final_actual_max = actual_max(f_linear, n)

In [ ]:
max_val,S_final_actual_max

We get the same output from the gradient descent as the exact output

### For f_polynomial

In [72]:
alpha = 0.01
epsilon = 10**(-5)

In [73]:
x_initial = np.random.uniform(0,1, n)
S_init = convert_x_to_S(x_initial)

In [74]:
print(x_initial,S_init)

[0.12097921 0.32270856 0.73057183 0.18291459 0.1168157  0.03979879
 0.49490506 0.57530526 0.92132405 0.2532028 ] [3, 8, 9]


In [75]:
_,_,x_final = gradient_ascent(F, x_initial, f_polynomial, n, alpha, t, epsilon)
S_final_grad_ascent = convert_x_to_S(x_final)

Iter:  1
Grad:  [0.3600459304459662, 0.9347091788554871, 0.9132999521138349, 0.03663891492779192, 0.5818846312370665, 0.8552428107360703, 0.3225197730497822, 0.3330112668016152, 0.04381309130864053, 0.31110776734708856]
x:  [0.12457967 0.33205566 0.73970483 0.18328097 0.12263455 0.04835122
 0.49813025 0.57863537 0.92176218 0.25631387]
Iter:  2
Grad:  [0.44608786606666717, 0.9263445879847709, 0.962339434029524, 0.1421453098317973, 0.506967870267611, 0.9023499368465597, 0.33509289321839963, 0.30553232605642466, 0.04897471815968246, 0.19890385048293768]
x:  [0.12904055 0.3413191  0.74932822 0.18470243 0.12770422 0.05737472
 0.50148118 0.58169069 0.92225193 0.25830291]
Iter:  3
Grad:  [0.27098637469254405, 0.9868644382015836, 0.975856124156537, 0.02072132373719282, 0.5436926982986565, 0.841454558371606, 0.3105778438538549, 0.4084086235226261, -0.012715724663394434, 0.2732399518182764]
x:  [0.13175041 0.35118775 0.75908678 0.18490964 0.13314115 0.06578926
 0.50458696 0.58577478 0.92212477 0

Iter:  27
Grad:  [0.4204371884516753, 0.8940441005930202, 0.9546885157723097, 0.0362573876292176, 0.5658418164811696, 0.9088754338605405, 0.277809968175307, 0.27455381615607166, -0.007056035225656121, 0.2547194304836329]
x:  [0.21873639 0.58022121 0.98465996 0.19088914 0.26598793 0.28719724
 0.58180399 0.67337853 0.92537195 0.32684624]
Iter:  28
Grad:  [0.4763928102412489, 0.9716238766040632, 0.9136086511970809, 0.03518178864215393, 0.4225994087426166, 0.9394030005819256, 0.29094797272174633, 0.359491030919056, -0.053665876238007115, 0.17140116296268326]
x:  [0.22350032 0.58993745 0.99379604 0.19124096 0.27021392 0.29659127
 0.58471347 0.67697344 0.92483529 0.32856025]
Iter:  29
Grad:  [0.28723636394963936, 0.9372442670580261, 0.8602716173235321, 0.09246581800575226, 0.6475872988865787, 0.9296496330462851, 0.17636810806732584, 0.37046433327062456, -0.008463786013124697, 0.4169580099941559]
x:  [0.22637268 0.59930989 1.         0.19216562 0.27668979 0.30588777
 0.58647715 0.68067809 0.9

Iter:  53
Grad:  [0.3282761015406428, 0.9329732977445113, 0.8793925448067266, -0.018460646857046292, 0.5395090459469274, 1.0125468062018057, 0.42790312975501266, 0.2801088432764556, 0.0038434235112516646, 0.24575502034606211]
x:  [0.30642624 0.8300577  1.         0.19889034 0.41680123 0.52372575
 0.66140324 0.76156582 0.92273495 0.39443732]
Iter:  54
Grad:  [0.2954334932935261, 0.9821997687477011, 0.9282905245842086, 0.04719868177575526, 0.5313735361645318, 0.9263773084849056, 0.3359131442820358, 0.4284601011680187, -0.044812917879645475, 0.24199282505577147]
x:  [0.30938058 0.8398797  1.         0.19936233 0.42211497 0.53298953
 0.66476237 0.76585042 0.92228683 0.39685725]
Iter:  55
Grad:  [0.34214589912102067, 1.0295059809543368, 0.9987860765130607, 0.0007751257339014828, 0.6524204371528075, 0.8901550492480497, 0.305949344869493, 0.3844070605202399, 0.0049129967798791085, 0.4288075716453341]
x:  [0.31280204 0.85017476 1.         0.19937008 0.42863917 0.54189108
 0.66782186 0.76969449

Iter:  78
Grad:  [0.34936985702244705, 0.9498575926351123, 0.9467031110318467, 0.031311889964088735, 0.6077182744397271, 0.9380665852798398, 0.3512268180937772, 0.28595327931030345, 0.014561419645324314, 0.33518277611279057]
x:  [0.39413459 1.         1.         0.20409482 0.55673643 0.7564354
 0.7446776  0.85368651 0.9194132  0.46581461]
Iter:  79
Grad:  [0.36796271170051664, 0.971466828860156, 0.7952627668660863, -0.014083692613890086, 0.5212439559693518, 0.9578398950960256, 0.3907708419562246, 0.3766517302961021, -0.0809787335161456, 0.24253903868700633]
x:  [0.39781422 1.         1.         0.20395398 0.56194887 0.7660138
 0.74858531 0.85745303 0.91860342 0.46824   ]
Iter:  80
Grad:  [0.3217803818014704, 0.9640901953602357, 0.9541666486357463, -0.01939225255378796, 0.5119272936333132, 0.9056330223156128, 0.3428103086126053, 0.4150573486900613, 0.03159615265334503, 0.2926359338751645]
x:  [0.40103202 1.         1.         0.20376006 0.56706815 0.77507013
 0.75201341 0.8616036  0.918

Iter:  104
Grad:  [0.3568838140047981, 1.002538459649554, 0.9659181424047554, -0.04251631114991561, 0.588247831856815, 0.9287129151744336, 0.3395190449361811, 0.3316425947416781, -0.0009333185429438728, 0.3114230054021778]
x:  [0.48229075 1.         1.         0.2093455  0.70010014 0.99811073
 0.82980404 0.94695088 0.92161095 0.53457544]
Iter:  105
Grad:  [0.30573286614149087, 0.9513009738806422, 0.8895023203955685, 0.0004210837623599417, 0.5553419126048138, 0.949097085324889, 0.3242718341382105, 0.3554667289286795, 0.02700820858344244, 0.31086636970727355]
x:  [0.48534808 1.         1.         0.20934971 0.70565356 1.
 0.83304676 0.95050555 0.92188103 0.5376841 ]
Iter:  106
Grad:  [0.32297576847420784, 0.947627581260746, 0.9156004322843496, -0.004807999189808676, 0.5188198557167611, 0.8975038924629546, 0.3188605994909679, 0.36021056859000256, -0.03638543896236435, 0.29570037114203185]
x:  [0.48857783 1.         1.         0.20930163 0.71084176 1.
 0.83623537 0.95410765 0.92151718 0.54

Iter:  130
Grad:  [0.3835368849313703, 0.9506244217229076, 0.8753643425648363, 0.03373466890531063, 0.5462167534264069, 0.9327444016979469, 0.3450021967110106, 0.33042111039163746, -0.06011364236151806, 0.2834854381990084]
x:  [0.57406081 1.         1.         0.21541776 0.8470801  1.
 0.9145899  1.         0.9208434  0.60407325]
Iter:  131
Grad:  [0.327021961749713, 1.0068963257748473, 0.9327217383624538, -0.039118930719609146, 0.5695535771262588, 0.9324104286260839, 0.36869982983126315, 0.35431412782129, 0.030471212178293072, 0.24685919716197002]
x:  [0.57733102 1.         1.         0.21502657 0.85277564 1.
 0.9182769  1.         0.92114811 0.60654184]
Iter:  132
Grad:  [0.334621909251573, 0.9327080842558844, 0.9169903552912704, 0.04630686313220078, 0.5931795054799576, 0.9265936173720641, 0.2922090263805357, 0.3245466012579761, -0.0050551581249012045, 0.2959124627540204]
x:  [0.58067724 1.         1.         0.21548964 0.85870743 1.
 0.92119899 1.         0.92109756 0.60950096]
Iter

Iter:  156
Grad:  [0.36355617713637933, 0.9368212422979103, 0.9216122452322559, 0.05953740317757639, 0.5581230634090213, 0.9143182238874057, 0.3336422706006186, 0.36188080623331675, -0.010383803243922962, 0.2598967303025068]
x:  [0.66590475 1.         1.         0.22307617 0.99230326 1.
 0.99802125 1.         0.92174487 0.67447165]
Iter:  157
Grad:  [0.3502453033876476, 0.9554725378001168, 0.9374352887971877, 0.02109691771395017, 0.5446624211190625, 0.9508311587598057, 0.29362059394402085, 0.32723312523229175, -0.004139442259825543, 0.24937912275105312]
x:  [0.66940721 1.         1.         0.22328714 0.99774988 1.
 1.         1.         0.92170348 0.67696544]
Iter:  158
Grad:  [0.3679641208452695, 0.9278079166839284, 0.9331629736884461, 0.03073833862974773, 0.5354690216205422, 0.9076544723479225, 0.3385138484073975, 0.351384483998614, 0.014796053660367292, 0.29465524557450706]
x:  [0.67308685 1.         1.         0.22359453 1.         1.
 1.         1.         0.92185144 0.67991199]


Iter:  182
Grad:  [0.34191231769358854, 0.9570364568017538, 0.9254163940380034, 0.0340693329267836, 0.5714316922651972, 0.9615852677893235, 0.2972064162811092, 0.36984202247076503, -0.013984373714778897, 0.24425219262437903]
x:  [0.7574194  1.         1.         0.22987154 1.         1.
 1.         1.         0.92336895 0.74326568]
Iter:  183
Grad:  [0.33868793393111485, 0.9659904977614859, 0.9448861469804934, 0.029271754847948195, 0.5396367808251545, 0.9213530354074901, 0.3412375692610352, 0.3707480245471908, -0.027656777352357054, 0.29156726207864825]
x:  [0.76080628 1.         1.         0.23016426 1.         1.
 1.         1.         0.92309239 0.74618135]
Iter:  184
Grad:  [0.34196197511547854, 0.9085412550573744, 0.9270306717945767, 0.026378236919329723, 0.5473063418641848, 0.9083658856715124, 0.3338812318685145, 0.3564963987537846, 0.009686452860696804, 0.2603986511742393]
x:  [0.7642259  1.         1.         0.23042804 1.         1.
 1.         1.         0.92318925 0.74878534

Iter:  208
Grad:  [0.3651912831684836, 0.9438925526420396, 0.9141191042492074, 0.0481038285510742, 0.5682339476034919, 0.9345251125150598, 0.3220327405984973, 0.3469083872302168, -0.02860384832380891, 0.2694342699796941]
x:  [0.84872433 1.         1.         0.23799246 1.         1.
 1.         1.         0.92252697 0.813065  ]
Iter:  209
Grad:  [0.34909600691430676, 0.9392697933905243, 0.9296849251253771, 0.036089742390082336, 0.5472754597205047, 0.9509471652324302, 0.3222228987454505, 0.34305491621267503, -0.013396665473146108, 0.27636642509159604]
x:  [0.85221529 1.         1.         0.23835336 1.         1.
 1.         1.         0.922393   0.81582867]
Iter:  210
Grad:  [0.35745437754170517, 0.9374861373177859, 0.9141827263317515, 0.04542479391469101, 0.5494972661919295, 0.9257355637887645, 0.3173421909711873, 0.3773063829621135, 0.008112363564139358, 0.2693590041068319]
x:  [0.85578983 1.         1.         0.23880761 1.         1.
 1.         1.         0.92247412 0.81852226]
It

Iter:  234
Grad:  [0.3485021369146155, 0.9464363948523351, 0.9175779274467533, 0.02648038346106585, 0.5646936898601966, 0.9182699414517681, 0.31717274136279183, 0.3613371561787071, 0.0011928759775114983, 0.27407763187128076]
x:  [0.93928408 1.         1.         0.24576343 1.         1.
 1.         1.         0.92268614 0.88212761]
Iter:  235
Grad:  [0.34236362566860823, 0.9395645746802157, 0.9302438201532834, -3.227683101236778e-06, 0.5468978048486912, 0.9263730928133214, 0.32125625578373196, 0.3353607780879866, 0.019757780678981263, 0.2663086500899787]
x:  [0.94270771 1.         1.         0.2457634  1.         1.
 1.         1.         0.92288372 0.8847907 ]
Iter:  236
Grad:  [0.3603572765363232, 0.9581487274238412, 0.9222562892275721, 0.023763715888247994, 0.5647257729295543, 0.9129019124505677, 0.32258819203747446, 0.35680730844480824, 0.01895112805258581, 0.27154975124386027]
x:  [0.94631129 1.         1.         0.24600103 1.         1.
 1.         1.         0.92307323 0.887506

Iter:  259
Grad:  [0.35405517495190164, 0.9486835432891545, 0.9102449254086173, 0.026117570227473408, 0.5670272405899919, 0.9286362062904367, 0.3300092202260174, 0.35373713049732114, -0.00711727972177556, 0.26607493535923155]
x:  [1.         1.         1.         0.25203281 1.         1.
 1.         1.         0.92329601 0.9481536 ]
Iter:  260
Grad:  [0.35662093699870123, 0.947127205535855, 0.9230456900505573, 0.020967931182590327, 0.56453579197332, 0.9217735256162141, 0.32146165080924316, 0.3441551353733985, -0.002179854329964037, 0.26516156714164474]
x:  [1.         1.         1.         0.25224249 1.         1.
 1.         1.         0.92327421 0.95080522]
Iter:  261
Grad:  [0.34555551451774225, 0.9454799497297341, 0.915580135548367, 0.030239431916894155, 0.5575596546039439, 0.9143612562304169, 0.32445793062799844, 0.35460060318233744, 0.0028717420890540524, 0.2640413614047681]
x:  [1.         1.         1.         0.25254488 1.         1.
 1.         1.         0.92330293 0.9534456

Iter:  285
Grad:  [0.34924291096551574, 0.9504227512553256, 0.9220179126950865, 0.02927079203295868, 0.5644162448123478, 0.9219414579811724, 0.3244312880698095, 0.3531225519590846, 0.002974684627329971, 0.26581433650217523]
x:  [1.         1.         1.         0.25949815 1.         1.
 1.         1.         0.9239553  1.        ]
Iter:  286
Grad:  [0.3512926133213119, 0.9513750246272483, 0.9229205286451254, 0.029217030695201984, 0.5628070981640203, 0.9230294069153957, 0.3263117858427398, 0.3502078665896802, 0.001604632300950648, 0.2640467375385427]
x:  [1.         1.         1.         0.25979032 1.         1.
 1.         1.         0.92397134 1.        ]
Iter:  287
Grad:  [0.35003135588835743, 0.9524939581462131, 0.9226156484999581, 0.029313801103165282, 0.5613766361481964, 0.9236768001421511, 0.3250344000084553, 0.3505342512699503, 0.0006912640833638406, 0.2671401075404374]
x:  [1.         1.         1.         0.26008346 1.         1.
 1.         1.         0.92397825 1.        ]
I

In [76]:
print(S_final_grad_ascent)

[1, 2, 3, 5, 6, 7, 8, 9, 10]


In [77]:
max_val,S_final_actual_max = actual_max(f_polynomial, n)

1 [10] 0.2644872932460099
3 [9, 10] 0.26586358349258316
4 [8] 0.3518008848366774
5 [8, 10] 0.6162881780826872
7 [8, 9, 10] 0.6176644683292605
12 [7, 8] 0.6765961905231962
13 [7, 8, 10] 0.9410834837692061
15 [7, 8, 9, 10] 0.9424597740157794
17 [6, 10] 1.1869673495605308
19 [6, 9, 10] 1.1883436398071041
20 [6, 8] 1.2742809411511984
21 [6, 8, 10] 1.5387682343972082
23 [6, 8, 9, 10] 1.5401445246437815
28 [6, 7, 8] 1.599076246837717
29 [6, 7, 8, 10] 1.8635635400837272
31 [6, 7, 8, 9, 10] 1.8649398303303002
53 [5, 6, 8, 10] 2.101009853559032
55 [5, 6, 8, 9, 10] 2.102386143805605
60 [5, 6, 7, 8] 2.1613178659995405
61 [5, 6, 7, 8, 10] 2.4258051592455505
63 [5, 6, 7, 8, 9, 10] 2.4271814494921236
125 [4, 5, 6, 7, 8, 10] 2.455032942208302
127 [4, 5, 6, 7, 8, 9, 10] 2.4564092324548756
149 [3, 6, 8, 10] 2.460454386278255
151 [3, 6, 8, 9, 10] 2.461830676524828
156 [3, 6, 7, 8] 2.520762398718764
157 [3, 6, 7, 8, 10] 2.785249691964774
159 [3, 6, 7, 8, 9, 10] 2.7866259822113473
181 [3, 5, 6, 8, 10] 3.0

In [78]:
max_val,S_final_actual_max

(4.6792183892414725, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

For the polynomial function the gradient ascent doesn't give the same output as the exact method