In [5]:
import random
import numpy as np
import itertools
import copy

## Multi linear approximation

In [6]:
def F(x, f, t):

    sum_R = 0

    for i in range(t):

        x_bar = np.random.uniform(0,1, x.shape)

        R_t = x >= x_bar

        sum_R = sum_R + f(R_t)

    return sum_R/t

## Function to calculate gradients

In [7]:
def get_gradient_F(F,x,f,t,n):
    
    x_new_1 = x*np.ones((n, n))
    x_new_0 = x*np.ones((n, n))

    np.fill_diagonal(x_new_1, 1)
    np.fill_diagonal(x_new_0, 0)
    
    return F(x_new_1, f, t) - F(x_new_0, f, t)

## Gradient ascent

In [21]:
def gradient_ascent(F, x, f, alpha, t, max_iter, n):
    
    x_init = copy.deepcopy(x)
    sum_init = F(x, f, t)
    
    # key values to be used
    sum_update = 0
    j = 0
    
    sum_temp = copy.deepcopy(sum_init)
    # start updating the parameters x with iterative gradients
    
    while (j<max_iter):
        
        j += 1
        sum_temp = F(x, f, t)
        
        grad = get_gradient_F(F,x,f,t,n)
        
        x = x + alpha*grad
        x = np.maximum(np.minimum(x,1),0)
        
        sum_update = F(x, f, t)
            
        #print("Iteration: ", j, "\n" , "Function value: ", sum_temp,"\n", "x: ", x, "\n")
        #print("Iteration: ", j, "\n" , "Function value: ", sum_temp,"\n", "grad: ", grad, "\n")
        
    
    return j,sum_update, x

## Linear function

In [9]:
def f_linear(x):
        
    return np.dot(a,x.T)

## Polynomial function

In [10]:
def f_polynomial(x):
    d,n = x.shape
    out = np.zeros((1,d))
    
    for i in range(0,d):
        
        x_i = x[i,:].reshape(1,n)
        x_square = np.dot(x_i.T,x_i)
        out[0,i] = np.sum(a_hat*x_square)
        
    return out

## Finding the actual argmax by going through all 2^n alternatives

In [11]:
def actual_max(f,n):
    
    A = [np.array(i) for i in itertools.product([0, 1], repeat = n)]
    
    max_val_S = 0
    argmax_s = []

    for i in range(len(A)):

        val_S = f(A[i].reshape(1,n))
        
        if val_S > max_val_S:
            max_val_S = val_S
            argmax_s = A[i]
            print(i,max_val_S, argmax_s)
    
    return max_val_S, argmax_s

## Testing for polynomial function

In [22]:
#parameters
alpha = 0.1 
max_iter = 100
t=500
n = 10

x_initial = np.random.uniform(0,1, (1,n))
print(x_initial)

[[0.13416285 0.86819873 0.68098077 0.08450305 0.80565954 0.85401028
  0.6224054  0.70118783 0.53592099 0.54770508]]


In [23]:
a_hat = np.linspace(-1, 1, n*n).reshape(n,n)
a_hat

array([[-1.        , -0.97979798, -0.95959596, -0.93939394, -0.91919192,
        -0.8989899 , -0.87878788, -0.85858586, -0.83838384, -0.81818182],
       [-0.7979798 , -0.77777778, -0.75757576, -0.73737374, -0.71717172,
        -0.6969697 , -0.67676768, -0.65656566, -0.63636364, -0.61616162],
       [-0.5959596 , -0.57575758, -0.55555556, -0.53535354, -0.51515152,
        -0.49494949, -0.47474747, -0.45454545, -0.43434343, -0.41414141],
       [-0.39393939, -0.37373737, -0.35353535, -0.33333333, -0.31313131,
        -0.29292929, -0.27272727, -0.25252525, -0.23232323, -0.21212121],
       [-0.19191919, -0.17171717, -0.15151515, -0.13131313, -0.11111111,
        -0.09090909, -0.07070707, -0.05050505, -0.03030303, -0.01010101],
       [ 0.01010101,  0.03030303,  0.05050505,  0.07070707,  0.09090909,
         0.11111111,  0.13131313,  0.15151515,  0.17171717,  0.19191919],
       [ 0.21212121,  0.23232323,  0.25252525,  0.27272727,  0.29292929,
         0.31313131,  0.33333333,  0.35353535

In [24]:
gradient_ascent(F, x_initial, f_polynomial, alpha, t, max_iter, n)

(100,
 array([[16.33333333]]),
 array([[0., 0., 0., 1., 1., 1., 1., 1., 1., 1.]]))

In [25]:
actual_max(f_polynomial,n)

1 [[1.]] [0 0 0 0 0 0 0 0 0 1]
3 [[3.55555556]] [0 0 0 0 0 0 0 0 1 1]
7 [[7.]] [0 0 0 0 0 0 0 1 1 1]
15 [[10.66666667]] [0 0 0 0 0 0 1 1 1 1]
31 [[13.88888889]] [0 0 0 0 0 1 1 1 1 1]
63 [[16.]] [0 0 0 0 1 1 1 1 1 1]
127 [[16.33333333]] [0 0 0 1 1 1 1 1 1 1]


(array([[16.33333333]]), array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1]))

## Testing for linear function

In [26]:
a = np.linspace(-1, 1, n).reshape(1,n)
print(a)
gradient_ascent(F, x_initial, f_linear, alpha, t, max_iter, n = 10)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]]


(100, array([[2.77777778]]), array([[0., 0., 0., 0., 0., 1., 1., 1., 1., 1.]]))

In [27]:
actual_max(f_linear,n)

1 [[1.]] [0 0 0 0 0 0 0 0 0 1]
3 [[1.77777778]] [0 0 0 0 0 0 0 0 1 1]
7 [[2.33333333]] [0 0 0 0 0 0 0 1 1 1]
15 [[2.66666667]] [0 0 0 0 0 0 1 1 1 1]
31 [[2.77777778]] [0 0 0 0 0 1 1 1 1 1]


(array([[2.77777778]]), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]))