In [1]:
import random
import numpy as np
import itertools
import copy

## Convert x to S

In [78]:
def convert_x_to_S(x):
    x_bar = 0.5*np.ones(len(x))
    s = x >= x_bar
    S = []

    for i in range(len(s)):

        if s[i] == True:
            S.append(i+1)
    
    return S

### F(x) without sampling (not used)

In [38]:
def F_without_sampling(x, f, n, t):
    
    A = [np.array(i) for i in itertools.product([0, 1], repeat = n)]
    
    val_S = 0

    for i in range(len(A)):

        prod_in_s = 1
        prod_not_in_s = 1
        S = []

        for j in range(len(A[i])):
            if A[i][j] == 1:
                prod_in_s = prod_in_s*x[j]
                S.append(j+1)
            else:
                prod_not_in_s = prod_not_in_s*(1-x[j])

        val_S = val_S + f(S)*prod_in_s*prod_not_in_s
    
    return val_S

### Approximation of F(x) using sampling 
define t

In [39]:
def F(x, f, n, t):
    
    sum_R = 0
    
    for i in range(t):
            
        x_bar = np.random.uniform(0,1, n)
        r_t = x >= x_bar
        R_t = []
            
        for i in range(len(r_t)):
            
            if r_t[i] == True:
                R_t.append(i+1)
                
        sum_R = sum_R + f(R_t)

    return sum_R/t

In [40]:
def get_gradient_F_for_i(F, x, f, n, i, t):


    x_without_i = copy.deepcopy(x)
    x_without_i[i] = 0.0

    x_with_i = copy.deepcopy(x)
    x_with_i[i] = 1.0

    # print('x with xi: ', x_with_i)
    # print('x without xi: ', x_without_i)

    df_dxi = F(x_with_i, f, n, t) - F(x_without_i, f, n, t)
    return df_dxi

In [41]:
def get_gradient_F(F, x, f, t):
    
    n = len(x)
    
    grad = np.zeros(len(x))
    
    for i in range(len(x)):
        
        grad[i] = get_gradient_F_for_i(F, x, f, n, i, t)
    
    return grad

## Testing

Define the size of the problem (n) 

In [42]:
n = 10
N = [(i+1) for i in range(n)]

Define an x vector

In [83]:
x_init = np.random.uniform(0,1, n)
print("x: ", x)

x:  [0.36317331 0.72496232 0.43511452 0.76232037 0.80955674 0.44895654
 0.1389388  0.09097997 0.56341361 0.15661356]


The corresponding S vector

In [85]:
S_init = convert_x_to_S(x_init)
S_init

[2, 4, 5, 7, 10]

In [46]:
t = int(2**n/4)

## Constant function f(s)

In [47]:
def f_constant(S):
    return 5

### Values of the function

Actual value

In [48]:
f_constant(S)

5

Multi-linear extenstion

In [51]:
F_without_sampling(x, f_constant, n, t)

4.999999999999998

Mutli-linear extension with sampling

In [52]:
F(x, f_constant, n, t)

5.0

### Values of the gradient using multi-linear extension

without sampling

In [49]:
get_gradient_F(F_without_sampling, x, f_constant, t)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

With sampling

In [50]:
get_gradient_F(F, x, f_constant, t)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Linear function f(S)

In [122]:
a = np.random.uniform(-1,1, n)
a

array([-0.59560234, -0.60060714, -0.08306493, -0.56550184,  0.08338033,
       -0.65249205,  0.32384115,  0.39270201, -0.08942853, -0.52571154])

In [54]:
def f_linear(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    return np.dot(a,s_hat)

### Values of the function

Actual value

In [55]:
f_linear(S)

0.15123459125837813

Multi-linear extenstion

In [56]:
F_without_sampling(x, f_linear, n, t)

-0.223845692862132

Mutli-linear extension with sampling

In [57]:
F(x, f_linear, n, t)

-0.22220760951854548

### Values of the gradient using multi-linear extension

without sampling

In [58]:
get_gradient_F(F_without_sampling, x, f_linear, t)

array([-0.56911368, -0.32727591, -0.19831385, -0.20853277,  0.68704327,
        0.61431227, -0.82463091, -0.57948346,  0.72695033,  0.00626648])

With sampling

In [59]:
get_gradient_F(F, x, f_linear, t)

array([-0.5209593 , -0.2548901 , -0.20920076, -0.21844023,  0.75493205,
        0.67286997, -0.74505285, -0.49024148,  0.73006711, -0.08481374])

## Polynomial f(S) function

In [60]:
def f_polynomial(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    a_hat = s_hat*a
    
    return np.dot(a_hat,a_hat)

### Values of function

Actual value

In [61]:
f_polynomial(S)

0.6226238874770083

Multi-linear extension 

In [62]:
F_without_sampling(x, f_polynomial, n, t)

1.2346439031360459

Multi-linear extenstion with sampling

In [63]:
F(x, f_polynomial, n, t)

1.2151348289837727

### Values of gradients using multi-linear approximation

Without sampling

In [64]:
get_gradient_F(F_without_sampling, x, f_polynomial, t)

array([3.23890380e-01, 1.07109518e-01, 3.93283841e-02, 4.34859169e-02,
       4.72028452e-01, 3.77379561e-01, 6.80016138e-01, 3.35801085e-01,
       5.28456775e-01, 3.92687246e-05])

With sampling

In [65]:
get_gradient_F(F, x, f_polynomial, t)

array([0.27406925, 0.09810465, 0.07319991, 0.07753057, 0.52099185,
       0.39098826, 0.6296    , 0.30472826, 0.54472102, 0.06190173])

# Testing Gradient Ascent

## Find maximum using gradient ascent

In [167]:
def gradient_ascent(F, x, f, n, alpha, t, epsilon):
    
    x_init = copy.deepcopy(x)
    sum_init = F(x, f, n, t)
    # key values to be used
    sum_update = 0
    iter = 0
    sum_temp = copy.deepcopy(sum_init)

    # start updating the parameters x with iterative gradients
    while np.abs(sum_temp - sum_update) > epsilon:
        iter += 1
        sum_temp = F(x, f, n, t)

        for i in range(n):
            grad_i = get_gradient_F_for_i(F, x, f, n, i, t)
            x[i] = np.minimum(x[i] + alpha * grad_i, 1.0)
            x[i] = np.maximum(x[i], 0.0)

        sum_update = F(x, f, n, t)

    print('Iterations: ', iter, '\n')
    print('Initial F: ', sum_init)
    print('Initial x: ', x_init, '\n')
    print('Final F: ', sum_update)
    print('Final x: ', x, '\n')
    return iter, sum_update, x

## Go through all the possible S and find the maximum

In [166]:
def actual_max(f,n):
    
    A = [np.array(i) for i in itertools.product([0, 1], repeat = n)]
    
    max_val_S = 0
    argmax_S = []

    for i in range(len(A)):

        S = []

        for j in range(len(A[i])):
            if A[i][j] == 1:
                S.append(j+1)

        val_S = f(S)
        
        if val_S > max_val_S:
            max_val_S = val_S
            argmax_S = S
            print(i,S,val_S)
    
    return max_val_S, argmax_S
    

In [156]:
# stepsize for gradient ascent
alpha = 0.001
epsilon = 10**(-9)

### For f_linear

In [172]:
x_initial = np.random.uniform(0,1, n)
S_init = convert_x_to_S(x_initial)

In [173]:
print(x_initial,S_init)

[0.22130807 0.96299877 0.54604114 0.05499354 0.87419238 0.6066409
 0.14848089 0.24386139 0.01034562 0.89132367] [2, 3, 5, 6, 10]


In [174]:
_,_,x_final = gradient_ascent(F, x_initial, f_linear, n, alpha, t, epsilon)
S_final_grad_ascent = convert_x_to_S(x_final)

Iterations:  2474 

Initial F:  -1.4721556230930073
Initial x:  [0.22130807 0.96299877 0.54604114 0.05499354 0.87419238 0.6066409
 0.14848089 0.24386139 0.01034562 0.89132367] 

Final F:  0.7597261711451427
Final x:  [0.         0.         0.34037559 0.         1.         0.
 0.9507759  1.         0.         0.        ] 



In [175]:
print(S_final_grad_ascent)

[5, 7, 8]


In [176]:
max_val,S_final_actual_max = actual_max(f_linear, n)

4 [8] 0.3927020102318308
12 [7, 8] 0.7165431576449142
44 [5, 7, 8] 0.7999234846133663


In [177]:
max_val,S_final_actual_max

(0.7999234846133663, [5, 7, 8])

We get the same output from the gradient descent as the exact output

### For f_polynomial

In [189]:
alpha = 0.001
epsilon = 10**(-9)

In [190]:
x_initial = np.random.uniform(0,1, n)
S_init = convert_x_to_S(x_initial)

In [191]:
print(x_initial,S_init)

[0.24811139 0.89848543 0.25392792 0.68502991 0.33534884 0.44996104
 0.73431626 0.3700837  0.83602245 0.97424866] [2, 4, 7, 9, 10]


In [192]:
_,_,x_final = gradient_ascent(F, x_initial, f_polynomial, n, alpha, t, epsilon)
S_final_grad_ascent = convert_x_to_S(x_final)

Iterations:  4699 

Initial F:  1.2313472178947806
Initial x:  [0.24811139 0.89848543 0.25392792 0.68502991 0.33534884 0.44996104
 0.73431626 0.3700837  0.83602245 0.97424866] 

Final F:  2.0084700316028288
Final x:  [1.         1.         0.28642479 1.         0.36678356 1.
 1.         1.         0.87481278 1.        ] 



In [193]:
print(S_final_grad_ascent)

[1, 2, 4, 6, 7, 8, 9, 10]


In [187]:
max_val,S_final_actual_max = actual_max(f_polynomial, n)

1 [10] 0.27637261951588765
3 [9, 10] 0.2843700820239184
5 [8, 10] 0.4305874883560086
7 [8, 9, 10] 0.43858495086403937
13 [7, 8, 10] 0.535460577113831
15 [7, 8, 9, 10] 0.5434580396218618
17 [6, 10] 0.7021184965887742
19 [6, 9, 10] 0.710115959096805
21 [6, 8, 10] 0.8563333654288952
23 [6, 8, 9, 10] 0.864330827936926
29 [6, 7, 8, 10] 0.9612064541867176
31 [6, 7, 8, 9, 10] 0.9692039166947484
63 [5, 6, 7, 8, 9, 10] 0.9761561956201142
81 [4, 6, 10] 1.0219108312507386
83 [4, 6, 9, 10] 1.0299082937587694
85 [4, 6, 8, 10] 1.1761257000908596
87 [4, 6, 8, 9, 10] 1.1841231625988904
93 [4, 6, 7, 8, 10] 1.280998788848682
95 [4, 6, 7, 8, 9, 10] 1.2889962513567128
127 [4, 5, 6, 7, 8, 9, 10] 1.2959485302820788
255 [3, 4, 5, 6, 7, 8, 9, 10] 1.3028483134857352
285 [2, 6, 7, 8, 10] 1.3219353857926857
287 [2, 6, 7, 8, 9, 10] 1.3299328483007167
319 [2, 5, 6, 7, 8, 9, 10] 1.3368851272260827
337 [2, 4, 6, 10] 1.3826397628567069
339 [2, 4, 6, 9, 10] 1.3906372253647377
341 [2, 4, 6, 8, 10] 1.5368546316968277
34

In [188]:
max_val,S_final_actual_max

(2.018319395339896, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

For the polynomial function the gradient ascent doesn't give the same output as the exact method