In [9]:
import random
import numpy as np

In [20]:
n = 10
x = np.random.uniform(0,1, n)

In [21]:
# define a function that returns all possible subsets of s
def powerset(s):
    x = len(s)
    power_set = []
    for i in range(1 << x):
       power_set.append([s[j] for j in range(x) if (i & (1 << j))])

    return power_set

### F(x) without sampling

In [22]:
def F(x, f, N):
    # print("power set of N")
    ps_N = powerset(N)
    # print('ps_N: ', ps_N)

    sum = 0
    for S in ps_N:
        if S == []:
            # print(len(N))
            # print('x in the loop: ', len(x))
            x_not_S = [1 - x[i - 1] for i in N]
            sum += f(S) * np.prod(x_not_S)
        else:
            x_S = [x[i - 1] for i in S]
            not_S = list(set(N) - set(S))
            # print(x_S)
            # print(not_S)
            x_S_na = [x[j - 1] for j in not_S]
            sum += f(S) * np.prod(x_S) * np.prod(x_S_na)

    return sum

### Approximation of F(x) using sampling 
define t

In [23]:
def F_approx(x, f, N):
    
    t= 100
    sum_R = 0
    
    for i in range(t):
            
        x_bar = np.random.uniform(0,1, n)
        r_t = x >= x_bar
        R_t = []
            
        for i in range(len(r_t)):
            
            if r_t[i] == True:
                R_t.append(i+1)
                
        sum_R = sum_R + f(R_t)

    return sum_R/t

In [24]:
print('Sum: ', F(x, f, N))

NameError: name 'f' is not defined

In [25]:
import copy
def get_gradient_F_for_i(F, x, f, N, i):


    x_without_i = copy.deepcopy(x)
    x_without_i[i] = 0.0

    x_with_i = copy.deepcopy(x)
    x_with_i[i] = 1.0

    # print('x with xi: ', x_with_i)
    # print('x without xi: ', x_without_i)

    df_dxi = F(x_with_i, f, N) - F(x_without_i, f, N)
    return df_dxi

In [26]:
i = 3
print('gradient: ', get_gradient_F_for_i(F_approx, x, f, N, i))

NameError: name 'f' is not defined

In [27]:
def get_gradient_F(F, x, f, N):
    
    grad = np.zeros(len(x))
    
    for i in range(len(x)):
        
        grad[i] = get_gradient_F_for_i(F, x, f, N, i)
    
    return grad

In [42]:
get_gradient_F(F, x, f, N)

NameError: name 'f' is not defined

### Gradient Ascent

In [58]:
# stepsize for gradient ascent
alpha = 0.2

def gradient_ascent(x_init, F, x, f, N, alpha):

    # key values to be used
    sum_update = 0
    iter = 0
    sum_temp = copy.deepcopy(sum_init)

    # start updating the parameters x with iterative gradients
    while np.abs(sum_temp - sum_update) > 10 ** (-2):
        iter += 1
        sum_temp = F(x, f, N)

        for i in range(n):
            grad_i = get_gradient_F_for_i(F, x, f, N, i)
            x[i] = np.minimum(x[i] + alpha * grad_i, 1.0)

        sum_update = F(x, f, N)

        print('x updated: ', x)
        print('sum updated: ', sum_update)

    print('Iterations: ', iter)
    print('Initial F: ', sum_init)
    print('Initial x: ', x_init)
    print('Final F: ', sum_update)
    print('Final x: ', x)
    return iter, sum_update, x


## Testing

In [59]:
## Multi-Linear Extension


## Key values
n = 5 # number of elements in set N
S_size = 3 # size of

N = [(i+1) for i in range(n)] # set N
S = random.sample(N, S_size) # subset S
print(S)

[2, 4, 5]


In [60]:
## function F: [0,1]^n -> R
## function f: 2^S -> R

n = 10
N = [(i+1) for i in range(n)]

## define an initial vector of x

x = np.random.uniform(0,1, n)
print("x: ", x)

x:  [0.86680993 0.85828124 0.89317483 0.45628207 0.6251218  0.14965974
 0.85409757 0.80813037 0.53210044 0.13508252]


In [61]:
def f_constant(S):
    return 5

In [62]:
get_gradient_F(F_approx, x, f_constant, N)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
get_gradient_F(F, x, f_constant, N)

array([ 8.30402546,  8.38655245,  8.05886458, 15.77560122, 11.51472814,
       48.09668281,  8.42763739,  8.90704944, 13.52774293, 53.28696561])

In [64]:
a = np.random.uniform(0,1, n)

In [65]:
a

array([0.2277992 , 0.96171371, 0.33795274, 0.53729322, 0.18763119,
       0.4083018 , 0.33753744, 0.24335669, 0.46735478, 0.08805139])

In [66]:
def f_linear(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    return np.dot(a,s_hat)

In [67]:
get_gradient_F(F_approx, x, f_linear, N)

array([0.15314022, 0.98377113, 0.22883276, 0.5378429 , 0.24424089,
       0.35696654, 0.45418135, 0.09878727, 0.45917412, 0.06288212])

In [68]:
get_gradient_F(F, x, f_linear, N)

array([ 3.15617059,  3.18753325,  3.06300614,  5.99585255,  4.37642715,
       18.28013326,  3.2031469 ,  3.38534486,  5.14151045, 20.25280586])

In [69]:
x_init = copy.deepcopy(x)
sum_init = F(x, f_linear, N)
gradient_ascent(x_init, F, x, f_linear, N, alpha)

x updated:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
sum updated:  1944.0599829673815
x updated:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
sum updated:  1944.0599829673815
Iterations:  2
Initial F:  2.735799994699164
Initial x:  [0.86680993 0.85828124 0.89317483 0.45628207 0.6251218  0.14965974
 0.85409757 0.80813037 0.53210044 0.13508252]
Final F:  1944.0599829673815
Final x:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


(2, 1944.0599829673815, array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [74]:
def f_polynomial(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    a_hat = s_hat*a
    
    return np.dot(a_hat,a_hat)

In [75]:
get_gradient_F(F_approx, x, f_polynomial, N)

array([0.05189248, 0.92489325, 0.11421205, 0.28868401, 0.03520546,
       0.16671036, 0.11393152, 0.05922248, 0.21842049, 0.00775305])

In [76]:
get_gradient_F(F, x, f_polynomial, N)

array([1014.23367654, 1014.23367654, 1014.23367654, 1014.23367654,
       1014.23367654, 1014.23367654, 1014.23367654, 1014.23367654,
       1014.23367654, 1014.23367654])

In [78]:
x_init = copy.deepcopy(x)
sum_init = F(x, f_polynomial, N)
gradient_ascent(x_init, F, x, f_polynomial, N, alpha)

x updated:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
sum updated:  1014.2336765370962
Iterations:  1
Initial F:  1014.2336765370962
Initial x:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Final F:  1014.2336765370962
Final x:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


(1, 1014.2336765370962, array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))