In [9]:
import random
import numpy as np

In [20]:
n = 10
x = np.random.uniform(0,1, n)

In [21]:
# define a function that returns all possible subsets of s
def powerset(s):
    x = len(s)
    power_set = []
    for i in range(1 << x):
       power_set.append([s[j] for j in range(x) if (i & (1 << j))])

    return power_set

### F(x) without sampling

In [22]:
def F(x, f, N):
    # print("power set of N")
    ps_N = powerset(N)
    # print('ps_N: ', ps_N)

    sum = 0
    for S in ps_N:
        if S == []:
            # print(len(N))
            # print('x in the loop: ', len(x))
            x_not_S = [1 - x[i - 1] for i in N]
            sum += f(S) * np.prod(x_not_S)
        else:
            x_S = [x[i - 1] for i in S]
            not_S = list(set(N) - set(S))
            # print(x_S)
            # print(not_S)
            x_S_na = [x[j - 1] for j in not_S]
            sum += f(S) * np.prod(x_S) * np.prod(x_S_na)

    return sum

### Approximation of F(x) using sampling 
define t

In [23]:
def F_approx(x, f, N):
    
    t= 100
    sum_R = 0
    
    for i in range(t):
            
        x_bar = np.random.uniform(0,1, n)
        r_t = x >= x_bar
        R_t = []
            
        for i in range(len(r_t)):
            
            if r_t[i] == True:
                R_t.append(i+1)
                
        sum_R = sum_R + f(R_t)

    return sum_R/t

In [99]:
# print('Sum: ', F(x, f, N))

In [25]:
import copy
def get_gradient_F_for_i(F, x, f, N, i):


    x_without_i = copy.deepcopy(x)
    x_without_i[i] = 0.0

    x_with_i = copy.deepcopy(x)
    x_with_i[i] = 1.0

    # print('x with xi: ', x_with_i)
    # print('x without xi: ', x_without_i)

    df_dxi = F(x_with_i, f, N) - F(x_without_i, f, N)
    return df_dxi

In [98]:
# i = 3
# print('gradient: ', get_gradient_F_for_i(F_approx, x, f, N, i))

In [27]:
def get_gradient_F(F, x, f, N):
    
    grad = np.zeros(len(x))
    
    for i in range(len(x)):
        
        grad[i] = get_gradient_F_for_i(F, x, f, N, i)
    
    return grad

In [97]:
# get_gradient_F(F, x, f, N)

### Gradient Ascent

In [58]:
# stepsize for gradient ascent
alpha = 0.2

def gradient_ascent(x_init, F, x, f, N, alpha):

    # key values to be used
    sum_update = 0
    iter = 0
    sum_temp = copy.deepcopy(sum_init)

    # start updating the parameters x with iterative gradients
    while np.abs(sum_temp - sum_update) > 10 ** (-2):
        iter += 1
        sum_temp = F(x, f, N)

        for i in range(n):
            grad_i = get_gradient_F_for_i(F, x, f, N, i)
            x[i] = np.minimum(x[i] + alpha * grad_i, 1.0)

        sum_update = F(x, f, N)

        print('x updated: ', x)
        print('sum updated: ', sum_update)

    print('Iterations: ', iter)
    print('Initial F: ', sum_init)
    print('Initial x: ', x_init)
    print('Final F: ', sum_update)
    print('Final x: ', x)
    return iter, sum_update, x


## Testing

In [59]:
## Multi-Linear Extension


## Key values
n = 5 # number of elements in set N
S_size = 3 # size of

N = [(i+1) for i in range(n)] # set N
S = random.sample(N, S_size) # subset S
print(S)

[2, 4, 5]


In [81]:
## function F: [0,1]^n -> R
## function f: 2^S -> R

n = 10
N = [(i+1) for i in range(n)]

## define an initial vector of x

x = np.random.uniform(0,1, n)
print("x: ", x)

x:  [3.16782228e-01 5.55591015e-04 1.84577367e-01 6.18966855e-01
 4.06658745e-01 7.57905930e-01 2.71531924e-01 6.34850359e-01
 5.11274018e-01 6.55948922e-01]


In [82]:
def f_constant(S):
    return 5

In [83]:
get_gradient_F(F_approx, x, f_constant, N)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
get_gradient_F(F, x, f_constant, N)

array([-4.19038926e-03,  3.29165979e+00,  1.57052878e-03, -1.49259015e-02,
       -6.97999269e-03, -2.57339087e-02, -2.60667296e-03, -1.57780219e-02,
       -1.03608615e-02, -1.70154639e-02])

In [85]:
a = np.random.uniform(0,1, n)

In [86]:
a

array([0.57752534, 0.89637823, 0.13701174, 0.74650805, 0.39714286,
       0.96045429, 0.83548525, 0.71808103, 0.16826208, 0.17470947])

In [87]:
def f_linear(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    return np.dot(a,s_hat)

In [88]:
get_gradient_F(F_approx, x, f_linear, N)

array([0.58173057, 0.97342796, 0.03516944, 0.68069529, 0.42592107,
       0.88020491, 0.89401086, 0.72060318, 0.10008324, 0.15232665])

In [89]:
get_gradient_F(F, x, f_linear, N)

array([3.24949543e-03, 1.85277007e+00, 5.57696981e-03, 1.66306547e-03,
       2.53131752e-03, 1.35819284e-03, 3.79101798e-03, 1.62145676e-03,
       2.01336733e-03, 1.56930268e-03])

In [90]:
x_init = copy.deepcopy(x)
sum_init = F(x, f_linear, N)
gradient_ascent(x_init, F, x, f_linear, N, alpha)

Iterations:  0
Initial F:  0.0010293824042785808
Initial x:  [3.16782228e-01 5.55591015e-04 1.84577367e-01 6.18966855e-01
 4.06658745e-01 7.57905930e-01 2.71531924e-01 6.34850359e-01
 5.11274018e-01 6.55948922e-01]
Final F:  0
Final x:  [3.16782228e-01 5.55591015e-04 1.84577367e-01 6.18966855e-01
 4.06658745e-01 7.57905930e-01 2.71531924e-01 6.34850359e-01
 5.11274018e-01 6.55948922e-01]


(0, 0, array([3.16782228e-01, 5.55591015e-04, 1.84577367e-01, 6.18966855e-01,
        4.06658745e-01, 7.57905930e-01, 2.71531924e-01, 6.34850359e-01,
        5.11274018e-01, 6.55948922e-01]))

In [91]:
F_approx(x, f_linear, N)

2.3435834100349067

In [92]:
def f_polynomial(S):
    
    #convert S to 0,1
    s_hat = np.zeros(n)
    
    for i in range(len(S)):
        
        s_hat[S[i]-1] = 1
        
    a_hat = s_hat*a
    
    return np.dot(a_hat,a_hat)

In [93]:
get_gradient_F(F_approx, x, f_polynomial, N)

array([ 0.42000073,  0.73077304, -0.03406368,  0.53921204,  0.18994538,
        0.93265915,  0.74104984,  0.39208339,  0.04542624,  0.01365854])

In [94]:
get_gradient_F(F, x, f_polynomial, N)

array([2.35438006e-03, 1.34240069e+00, 4.04072165e-03, 1.20495267e-03,
       1.83403350e-03, 9.84061126e-04, 2.74673325e-03, 1.17480561e-03,
       1.45875937e-03, 1.13701805e-03])

In [95]:
x_init = copy.deepcopy(x)
sum_init = F(x, f_polynomial, N)
gradient_ascent(x_init, F, x, f_polynomial, N, alpha)

Iterations:  0
Initial F:  0.0007458257628314309
Initial x:  [3.16782228e-01 5.55591015e-04 1.84577367e-01 6.18966855e-01
 4.06658745e-01 7.57905930e-01 2.71531924e-01 6.34850359e-01
 5.11274018e-01 6.55948922e-01]
Final F:  0
Final x:  [3.16782228e-01 5.55591015e-04 1.84577367e-01 6.18966855e-01
 4.06658745e-01 7.57905930e-01 2.71531924e-01 6.34850359e-01
 5.11274018e-01 6.55948922e-01]


(0, 0, array([3.16782228e-01, 5.55591015e-04, 1.84577367e-01, 6.18966855e-01,
        4.06658745e-01, 7.57905930e-01, 2.71531924e-01, 6.34850359e-01,
        5.11274018e-01, 6.55948922e-01]))

In [96]:
F_approx(x, f_polynomial, N)

1.8107783664291635